services:
  # The Database Service
  postgres:
    image: postgres:16-alpine
    container_name: fintech-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fintech_ledger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintech-network

  # Database GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: fintech-pgadmin
    environment:
      - PGADMIN_DEFAULT_MAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fintech-network

  # Ledger Service
  ledger-api:
    build:
      context: .
      dockerfile: cmd/ledger-service/Dockerfile
    container_name: fintech-ledger-api
    ports:
      - "8081:8081"
    environment:
      # Docker internal DNS: Connect using the database container name!
      - DB_SOURCE=postgresql://root:secret@fintech-postgres:5432/fintech_ledger?sslmode=disable
      - SERVER_ADDRESS=:8081
    depends_on:
      - postgres
    networks:
      - fintech-network
  
volumes:
  postgres_data:

networks:
  fintech-network:
    driver: bridge
